export const Colors = {
  light: {
    background: '#efefef',
    cardBackground: '#FFFFFF',
    textPrimary: '#1A202C',
    textSecondary: '#718096',
    buttonBackground: '#3182CE',
    buttonText: '#FFFFFF',
    borderColor: '#E2E8F0',
    removeButton: '#E53E3E',
    toggleBackground: '#CBD5E0',
    inputBackground: '#EDF2F7',
    navBarBackground: '#FFFFFF',
    navBorderColor: '#E2E8F0',
    socialLinkBackground: '#EDF2F7',
    changePhotoButtonBackground: '#3182CE',
    logoutButtonBackground: '#E53E3E',
  },
  dark: {
    background: '#1A202C',
    cardBackground: '#2D3748',
    textPrimary: '#E2E8F0',
    textSecondary: '#A0AEC0',
    buttonBackground: '#3182CE',
    buttonText: '#FFFFFF',
    borderColor: '#4A5568',
    removeButton: '#E53E3E',
    toggleBackground: '#3182CE',
    inputBackground: '#4A5568',
    navBarBackground: '#2D3748',
    navBorderColor: '#4A5568',
    socialLinkBackground: '#4A5568',
    changePhotoButtonBackground: '#3182CE',
    logoutButtonBackground: '#E53E3E',
  },
};
